Re-submission of PR with merge issues corrected
nasa/HyperCP pull request #250
Opened 2024-10-03 08:36 UTC by ARamsay17

Improvements to uncertainty breakdown plots
Minor cleanup of PIU.py (cleanup will continue)

2024-10-04 14:54 UTC, oceancolorcoder requested changes
@ARamsay17, Please reply to the review question on PL1AQC. 

Also, please list how the changes were tested prior to the PR (sample pySAS? TriOS? L0-L2? Regime?)

2024-10-04 14:54 UTC, oceancolorcoder commented on Source/ProcessL1aqc.py
@ARamsay17 why was this change made? I put these in yesterday for clarity and to resolve the type class error we were getting with "DATETIME_ADJUSTED"

2024-10-04 14:54 UTC, oceancolorcoder commented on Source/ProcessL1aqc.py
@ARamsay17?

2024-10-04 16:28 UTC, ARamsay17 commented on Source/ProcessL1aqc.py
@oceancolorcoder I'm confused myself as I don't recall ever making this change. Please revert

2024-10-16 14:15 UTC, oceancolorcoder commented
Closing in favor of a new PR to come.

2024-10-16 14:15 UTC, closed without merging